export const CHATS_REQUEST = "CHATS_REQUEST"
export const CHATS_SUCCESS = "CHATS_SUCCESS"
export const CHATS_FAIL = "CHATS_FAIL"

export const CHAT_REQUEST = "CHAT_REQUEST"
export const CHAT_SUCCESS = "CHAT_SUCCESS"
export const CHAT_FAIL = "CHAT_FAIL"

export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST"
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS"
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL"